export const STORAGE_KEYS = {
  onboarded: 'flow-onboarded',
  expenses: 'flow-expenses',
  categories: 'flow-categories',
  budgets: 'flow-budgets',
  notes: 'flow-notes',
  dateEvents: 'flow-date-events',
  userProfile: 'flow-user-profile',
  currency: 'flow-currency',
  experimentalSettings: 'flow-experimental-settings',
  colorPalette: 'flow-color-palette',
  graphStyle: 'flow-graph-style',
  graphXAxis: 'flow-graph-xaxis',
  expenseRemindersEnabled: 'flow-expense-reminders-enabled',
  lastExpenseAddedAt: 'flow-last-expense-added-at',
  replaceInProgress: 'flow-replace-in-progress',
  isSampleData: 'flow-is-sample-data'
} as const;

export const FLOW_OWNED_KEYS = [
  'flow-onboarded',
  'flow-expenses',
  'flow-categories',
  'flow-budgets',
  'flow-notes',
  'flow-date-events',
  'flow-user-profile',
  'flow-currency',
  'flow-experimental-settings',
  'flow-color-palette',
  'flow-graph-style',
  'flow-graph-xaxis',
  'flow-expense-reminders-enabled',
  'flow-last-expense-added-at',
  'flow-replace-in-progress',
  'flow-is-sample-data',
  'flow.storage.migration.v1.completed',
  'flow.storage.baselineMigration.completed',
  'flow.storage.avatarMigration.completed',
  'flow-theme-v2',
  'flow-auto-backup-enabled',
  'flow-auto-backup-retention',
  'flow-last-auto-backup-at',
  'flow-last-auto-backup-status',
  'flow-last-auto-backup-file-name',
  'flow-last-auto-backup-error',
  'flow-auto-backup-payload',
  'developerOptionsEnabled',
  'flow-developerOptionsEnabled',
  'developerOptions',
  'flow-welcome-step',
  'flow-current-step',
  'flow-setup-draft',
  'flow-redirect-target'
] as const;

